name: CI Pipeline

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
    
permissions:
  contents: read
  packages: write
  
jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node-version: '22'
      image-name: ${{ github.repository }}
    secrets: inherit